SELECT * 
FROM EMPLOYEES;

SELECT JOB_ID
    , AVG(SALARY) AS Æò±Õ¿¬ºÀ
    FROM EMPLOYEES
    HAVING AVG(SALARY) >13000
    GROUP BY JOB_ID;
    
SELECT * 
     FROM (SELECT EMPLOYEE_ID
         , EMAIL
         , SALARY
          FROM EMPLOYEES
         ORDER BY SALARY DESC)
     WHERE ROWNUM <=5;

SELECT *
 FROM DEPARTMENTS;
 

SELECT A.DEPARTMENT_ID
              , A.DEPARTMENT_NAME
               , A. MANAGER_ID
                ,B.FIRST_NAME
                ,B.LAST_NAME
                FROM DEPARTMENTS A LEFT OUTER JOIN
                 EMPLOYEES B ON( A.MANAGER_ID = 
                 B.EMPLOYEE_ID)
                 WHERE A.LOCATION_ID = 1700;      
  --11¹ø               
CREATE TABLE TB_STUDENT(
    STUDENT_ID NUMBER(3,0) NOT NULL ,
    STUDENT_NAME VARCHAR2(50) NOT NULL ,
    AGE NUMBER(3,0) DEFAULT 20 ,
     MAJOR_ID VARCHAR2(50) );
CREATE TABLE TB_MAJOR(
   MAJOR_ID VARCHAR2(50) NOT NULL ,
  MAJOR_NAME VARCHAR2(100) NOT NULL,
 INST_DY      VARCHAR2(8) NOT NULL);
 SELECT *
 FROM TB_STUDENT;
 
 ALTER TABLE TB_STUDENT ADD CONSTRAINT PK_STUDENT 
 PRIMARY KEY(STUDENT_ID);
 
 ALTER TABLE TB_MAJOR ADD CONSTRAINT PK_MAJOR 
 PRIMARY KEY(MAJOR_ID);
 
 INSERT INTO TB_MAJOR(
 MAJOR_ID
 , MAJOR_NAME
 ,INST_DY
 ) VALUES(
 'M0001'
 , 'Á¤º¸°øÇÐ°ú'
 , '19960201');
 INSERT INTO TB_MAJOR(
 MAJOR_ID
 , MAJOR_NAME
 ,INST_DY
 ) VALUES(
 'M0002'
 ,'°æ¿µÇÐ°ú'
 ,'20000302');
 --11-5¹ø
 ALTER TABLE TB_STUDENT MODIFY( STUDENT_ID NUMBER(5,0));
 INSERT INTO TB_STUDENT(
STUDENT_ID
 , STUDENT_NAME
 ,AGE
 ,MAJOR_ID
 ) VALUES(
 1000
 , '±èÃ¶¼ö'
 , 20
 , 'M0001');
 
 INSERT INTO TB_STUDENT(
 STUDENT_ID
 , STUDENT_NAME
 ,AGE
 ,MAJOR_ID
 ) VALUES(
2000
 ,'È«±æµ¿'
 ,21
 ,'M0002');
 SELECT * 
 FROM TB_MAJOR;
UPDATE TB_MAJOR 
SET MAJOR_NAME = 'ÀÎ°øÁö´ÉÀ¶ÇÕ°ú'
WHERE MAJOR_ID = 'M0001'; 

DELETE FROM TB_STUDENT
WHERE STUDENT_ID = 1000;
SELECT *
FROM TB_STUDENT;


--NO.9
SELECT * 
FROM(
SELECT  A.EMPLOYEE_ID
      , A.EMAIL
      , A.SALARY
      , B.DEPARTMENT_NAME
      , B.LOCATION_ID
      FROM EMPLOYEES A
          ,DEPARTMENTS B
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
     ORDER BY SALARY DESC)
WHERE ROWNUM <=4;
       --AND EMPLOYEES.SALARY >= 14000;
SELECT * 
FROM(
SELECT  A.EMPLOYEE_ID
      , A.EMAIL
      , A.SALARY
      , B.DEPARTMENT_NAME
      , B.LOCATION_ID
      FROM EMPLOYEES A
          ,DEPARTMENTS B
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID)
WHERE SALARY > = 14000;

SELECT A.EMPLOYEE_ID
, A.EMAIL
, A.SALARY
,B.DEPARTMENT_NAME
FROM EMPLOYEES A
, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID;