CREATE TABLE MEMBER(
       ID VARCHAR2(50) PRIMARY KEY
     , PW VARCHAR2(50) NOT NULL
     , NICK VARCHAR2(50) NOT NULL
);
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES (
     'ADMIN', '12345','°ü¸®ÀÚ');
COMMIT;
SELECT * FROM MEMBER;

CREATE TABLE BOOK(
     TITLE VARCHAR2(50)
     , NAME VARCHAR2(50)
     , PRICE NUMBER
     , NUM VARCHAR2(50));
SELECT * FROM BOOK;

     