DROP TABLE TAB3;
CREATE TABLE TAB3 (
       COL1 VARCHAR2(100)
     , COL2 VARCHAR2(100));
INSERT INTO TAB3(COL1, COL2) VALUES('A','A');
INSERT INTO TAB3(COL1, COL2) VALUES('B','B');

COMMIT;

INSERT INTO TAB3(COL1, COL2) VALUES('C','C');
ROLLBACK;
SELECT *   
    FROM TAB3;
INSERT INTO TAB3(COL1, COL2) VALUES('D', 'D');

SAVEPOINT SV1;
INSERT INTO TAB3(COL1,COL2) VALUES('E','E');
ROLLBACK TO SV1; COMMIT;
SELECT* 
     FROM TAB3;
     
DROP TABLE TAB4;  
CREATE TABLE TAB4(
        COL1 VARCHAR2(10)
       , COL2 VARCHAR2(10));
       
INSERT INTO TAB4(COL1, COL2) VALUES('A', 'A');
COMMIT;
INSERT INTO TAB4(COL1, COL2) VALUES('B','B');
INSERT INTO TAB4(COL1, COL2) VALUES('C','C');
CREATE TABLE HELLO(COL1 VARCHAR2(10)
                   , COL2 VARCHAR2(10));
INSERT INTO TAB4(COL1, COL2 ) VALUES('D','D');
ROLLBACK;
SELECT * FROM TAB4;
INSERT INTO TAB4(COL1 , COL2) VALUES('E','E');
COMMIT;
SELECT * FROM TAB4;

