--1.먼저 작성(기존에 있던 FK_MEMBER라는 FOREIGN KEY 제약조건을 제거한다.)
ALTER TABLE TB_MEMBER_TEL DROP CONSTRAINT FK_MEMBER;
--2. 다시 FK_MEMBER라는 이름으로 FOREIGN KEY 제약조건을 생성한다.
ALTER TABLE TB_MEMBER_TEL ADD CONSTRAINT FK_MEMBER
FOREIGN KEY(MEMBER_ID) REFERENCES TB_MEMBER(MEMBER_ID);

--3.
--FK_MEMBER 라는 제약조건이 없다면! TB_MEMBER_TEL 테이블에는 아무MEMBER_ID나 사용해도 된다.
-- FK_MEMBER라는 제약조건이 생기면! TB_MEMBER_TEL테이블은 TB_MEMBER가 가진 MEMBER_ID만 사용해도 된다.
SELECT * FROM TB_MEMBER;
SELECT * FROM TB_MEMBER_TEL;

COMMIT;



--1번)
CREATE TABLE STUDENT(
     학생ID VARCHAR2(10) NOT NULL
     , 학생이름 VARCHAR2(20) NOT NULL
     , 가입일시 DATE DEFAULT SYSDATE
     , 나이 NUMBER DEFAULT 0);
   
     
CREATE TABLE STUDENT_TEL(
     학생ID VARCHAR2(10) NOT NULL
     , 구분코드 VARCHAR2(10) NOT NULL
    ,연락처 VARCHAR2(15) NOT NULL);
    
CREATE TABLE STUDENT_ADDR(
      학생ID VARCHAR(10) NOT NULL
, 도로명주소 VARCHAR(200) NOT NULL );


  ALTER TABLE STUDENT ADD CONSTRAINT  PK_STUDENT PRIMARY KEY(학생ID);
  ALTER TABLE STUDENT_TEL ADD CONSTRAINT  PK_STUDENT_TEL PRIMARY KEY(학생ID, 구분코드);
  ALTER TABLE STUDENT ADD CONSTRAINT  PK_STUDENT PRIMARY KEY(학생ID);

  ALTER TABLE STUDENT ADD CONSTRAINT  FK_STUDENT_TEL FOREIGN KEY(학생ID) REFERENCES STUDENT(학생ID);
  ALTER TABLE STUDENT_ADDR   ADD CONSTRAINT FK_STUDENT_ADDR FOREIGN KEY(학생ID) REFERENCES STUDENT (학생ID);
  
  ALTER TABLE TB_MEMBER ADD( BIRTH VARCHAR2(8));
  SELECT * FROM TB_MEMBER;
  ALTER TABLE TB_MEMBER DROP COLUMN BIRTH;
  ALTER TABLE TB_MEMBER MODIFY (PASSWD VARCHAR2(100));
  ALTER TABLE STUDENT RENAME COLUMN 학생ID TO STUDENT_ID;
  SELECT * FROM STUDENT;
  
  CREATE SEQUENCE ORDER_NO_SEQ
         INCREMENT BY 1 --증가할 값 1씩 증가함.
         START WITH 1; --1부터 시작한다
 SELECT ORDER_NO_SEQ.NEXTVAL
     FROM DUAL;
 INSERT INTO TB_ORDER(
        ORDER_NO
      , MEMBER_ID
      , PRD_ID
      ,ORDER_DATE
      ,ORDER_CNT
      , ORDER_PRICE)
VALUES( ORDER_NO_SEQ.NEXTVAL
       , 'BBBBB'
       , 'P0003'
       ,SYSDATE
       ,2
       ,120000);
DROP SEQUENCE ORDER_NO_SEQ;

SELECT *
  FROM MEMBER_SIMPLE_VIEW --마치 테이블처럼
 WHERE MEMBER_ID = 'BBBBB';
 

CREATE VIEW MEMBER_SIMPLE_VIEW AS 
SELECT A.MEMBER_ID
     , A.GRADE_CD
     , B.TEL_NO
  FROM TB_MEMBER A
     , TB_MEMBER_TEL B
  WHERE A.MEMBER_ID = B.MEMBER_ID
    AND B.TEL_DV_CD = '휴대폰';
