DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(50) NOT NULL,
    NICK VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(100) NOT NULL,
    GENDER VARCHAR2(100) NOT NULL,
    AGE NUMBER NOT NULL 
    );
    
INSERT INTO MEMBER VALUES('admin','1234','관리자','admin@google.com','010-2344-2222','남자',20);
COMMIT;

SELECT * FROM MEMBER;
    ROLLBACK;
    
    